### ISSUE TITLE
Hibernate Module

### ISSUE THREAD

**Issue by JGulbronson** [square/misk#10]
Currently the Hibernate Service does nothing of note, it starts up and it shuts down. This needs to be fleshed out to support querying and modifying a database. The main points will look something like:

- Supporting config based on environment (#1 and #2)
- Able to read database secrets securely (#8)
- Allowing database objects to be registered
- Allow simple operations such as INSERT, UPDATE, SELECT

**Comment by swankjesse** [comment]
We have a Hibernate module now. I’m going to close this and address more Hibernate stuff as separate issues.
