### ISSUE TITLE
Provide a database connection pool

### ISSUE THREAD

**Issue by maniksurtani** [square/misk#11]
Possibly making use of HikariCP. This is a pre-requisite for for Issue #10

**Comment by JGulbronson** [comment]
Looks like if we use at least Hibernate 4.3.6 (and I believe @swankjesse wants to go with Hibernate 5, we don't need HikariCP: https://github.com/brettwooldridge/HikariCP/wiki/Hibernate4

**Comment by swankjesse** [comment]
It’s done.
