### ISSUE TITLE
Add support for distributed tracing

### ISSUE THREAD

**Issue by maniksurtani** [square/misk#16]
With adapters for [StackDriver](https://cloud.google.com/trace/docs/reference/) tracing, as well as [Zipkin](https://github.com/openzipkin/zipkin).

**Comment by mmihic** [comment]
IMO should be an integration of http://opentracing.io/

**Comment by maniksurtani** [comment]
Also, this is a thing that's happening - https://github.com/TraceContext/tracecontext-spec

**Comment by swankjesse** [comment]
Basics here are in for both Zipkin and Jaeger.

**Comment by adriancole** [comment]
fyi opentracing breaks compat on every release and are also merging somehow to make "opentelemetry" unsolicited 2p is to support what's most effective and efficient per backend vs relying on a moving target api

**Comment by adriancole** [comment]
ex you will be getting this problem soon, too (if anyone is using the OT support) https://github.com/instana/instana-java-opentracing/issues/5
