### ISSUE TITLE
Misk should support some concept of environments

### ISSUE THREAD

**Issue by JGulbronson** [square/misk#2]
This will be useful when determining which yaml files for parse for config, as mentioned in #1. Examples of environments are testing, staging, production, etc.

A simple implementation could just be a String that gets bound so you can inject it like
```java
@Inject @Env String environment
```

Misk can provide a module that binds based of an environment variable. Alternatively a module can statically provide an environment, and then an app can select which to install.

**Comment by maniksurtani** [comment]
Should they be Strings, though? Maybe an `Environment` interface, and the default impl could be an enum with the more common set of `{DEVELOPMENT, STAGING, PRODUCTION}`.
