### ISSUE TITLE
Session.update()

### ISSUE THREAD

**Issue by swankjesse** [square/misk#220]
We should add this, and it should be off-by-default. Ie. we should attempt to configure Hibernate to require an explicit call to `Session.update()`.

**Comment by dhanji** [comment]
basically just `org.hibernate.flushMode=MANUAL`
but this will be a big change from how we are used to things working and may require developers to keep both systems in mind.

Do we want to have that split behavior?

**Comment by swankjesse** [comment]
Discussed offline. The current behavior is so familiar we shouldn’t intervene.
