### ISSUE TITLE
Compiled `module-info.class` in published jars

### ISSUE THREAD

**Issue by sormuras** [square/misk#252]
Due to https://github.com/johnrengelman/shadow/issues/352 these 3 published jars report as `org.slf4j` on the `module-path`.

- | [Misk Chat Project](https://github.com/square/misk/) | **:dvd:`org.slf4j`** | com.squareup.misk:[chat](https://mvnrepository.com/artifact/com.squareup.misk/chat):0.2.5 |
- | [Misk Exemplar Project](https://github.com/square/misk/) | **:dvd:`org.slf4j`** | com.squareup.misk:[exemplar](https://mvnrepository.com/artifact/com.squareup.misk/exemplar):0.2.5 |
- | [urlshortener](https://github.com/square/misk/) | **:dvd:`org.slf4j`** | com.squareup.misk:[urlshortener](https://mvnrepository.com/artifact/com.squareup.misk/urlshortener):0.2.5 |

See details at https://github.com/jodastephen/jpms-module-names/issues/16

**Comment by swankjesse** [comment]
Thanks for reporting this. Can fix.

**Comment by swankjesse** [comment]
Fix: https://github.com/square/misk/pull/280
