### ISSUE TITLE
ExecutorServiceModule

### ISSUE THREAD

**Issue by swankjesse** [square/misk#284]
I want very regular access to executor services. Something like this:

```
  install(ExecutorServiceModule(Jetty::class, thread_count = 5))
```

```
   @Inject @Jetty lateinit var executorService: ExecutorService
```

**Comment by swankjesse** [comment]
These should use a Service to shut themselves down.

In tests they could cheat such that all tests shared a small number of ExecutorServices that are never shut down. (Spinning up and tearing down executor services is problematic for test suites.)

**Comment by jjestrel** [comment]
there's enough `ExecutorService`s used that this seems worthwhile. will look with @monkey-mas
