### ISSUE TITLE
Update to use JUnit 5

### ISSUE THREAD

**Issue by maniksurtani** [square/misk#3]
This repo uses JUnit 4 for now, but we should be using the latest and greatest here.

**Comment by swankjesse** [comment]
Is JUnit 5 good? I don’t think we should do this too eagerly. We definitely should wait until IDE support is solid.

![](http://junit.org/junit5/docs/current/user-guide/images/component-diagram.svg)

**Comment by maniksurtani** [comment]
There are some nice new features in the way parameterized tests are written, exceptions and timeouts are tested for, etc. IDE support seems solid - IntelliJ [has supported it](https://blog.jetbrains.com/idea/2016/08/using-junit-5-in-intellij-idea/) for almost a year and a half now.

**Comment by JGulbronson** [comment]
@maniksurtani because Junit 5 lacks Rules, it doesn't seem like we can customize our injector per test. Because of that I'm going to put the upgrade on ice for now, and we can revisit later.

**Comment by maniksurtani** [comment]
Reading thru http://www.codeaffine.com/2016/04/06/replace-rules-in-junit5/ there are equivalent techniques. I'll take a stab at it if I find some free time this week.
