### ISSUE TITLE
Should resource loader paths not look like file paths?

### ISSUE THREAD

**Issue by swankjesse** [square/misk#342]
Ie. should resource identifiers look like they do today:

```
      /filesystem/etc/certs/url_shortener_key_combo.pem
      /resources/certs/url_shortener_key_combo.pem
      /memory/certs/url_shortener_key_combo.pem
```

Or like this:

```
      file:/etc/certs/url_shortener_key_combo.pem
      resources:/certs/url_shortener_key_combo.pem
      memory:/certs/url_shortener_key_combo.pem
```

Or something else?

**Comment by mmihic** [comment]
I was thinking the latter, the former seems confusing (albeit has Unix precedent)

**Comment by swankjesse** [comment]
It’s out for review. One more option – should the classpath resources have the scheme `resources:` as they do now, or should it be `classpath:` ?

**Comment by mmihic** [comment]
IMO ``classpath:``
