### ISSUE TITLE
QueryFactory `@OrderBy`

### ISSUE THREAD

**Issue by swankjesse** [square/misk#346]
This should be just as easy as `@Constraint`.

**Comment by swankjesse** [comment]
When this is done we should fix ReflectionQueryFactoryTest.kt to use `containsExactly(...)` rather than `hasSize(...)`.

**Comment by tirsen** [comment]
I actually built this (in a hacky way) but unfortunately Vitess doesn't yet support sorting on alpha columns for scatter queries and it can't sort on `id` unless the `id` is part of the `SELECT` clause projection. So we can get it to work but it will be a bit of work.

**Comment by swankjesse** [comment]
@lkerford did this in October!
