### ISSUE TITLE
Switch to using prometheus metrics library

### ISSUE THREAD

**Issue by mmihic** [square/misk#354]
Most modern metrics backends (including SignalFX) have native support for tagging and labeling metrics. Misk currently uses Dropwizard metrics, which does not have this support and thus requires some sort of translation layer to go from a flat metrics hierarchy to tagged metrics. We should switch from using dropwizard to using the prometheus metrics library, which has native tagging support and is also generally just more modernized, with support for features like native non-timer histograms, externally aggregatible timers, and more.

**Comment by jjestrel** [comment]
This is done
