### ISSUE TITLE
Nuke urlshortener example

### ISSUE THREAD

**Issue by adrw** [square/misk#506]

**Comment by JGulbronson** [comment]
Urlshortener seems to be the only place that Misk shows an example of persistence. What's the purpose of removing it?

**Comment by adrw** [comment]
@JGulbronson UrlShortener is now used internally as an example service. It's becoming confusing having two identically named services; one internal, and one open source in this package. Thus, removing this example and replacing at a later date with one to showcase persistence for open source users.
