### ISSUE TITLE
Metrics Module

### ISSUE THREAD

**Issue by JGulbronson** [square/misk#6]
Misk should offer an opinionated metrics service that acts as a facade to multiple backends.

For example, the counter, timer, gauge, and histogram models are all commonly used.

See [Dropwizard metrics](http://metrics.dropwizard.io/3.2.3/getting-started.html) and [Prometheus](https://prometheus.io/docs/concepts/metric_types/) for examples.

**Comment by maniksurtani** [comment]
Also, should have adapters to emit metrics to [StackDriver](https://cloud.google.com/monitoring/api/metrics) and [SignalFX](https://github.com/signalfx/signalfx-java).

**Comment by mmihic** [comment]
Why would this not just be an integration of yammer metrics? It's already implemented and widely known. I don't think we should be building our own implementation of widely adopted existing open source projects, particularly not in non-core areas like metrics.
