### ISSUE TITLE
Pagerduty Module

### ISSUE THREAD

**Issue by JGulbronson** [square/misk#7]
A Pagerduty service would offer easy alerting to Pagerduty, by accepting an API key and creating incidents directly.

Other services like Jetty could alert if there are too many 500's over a time period, as a simple example.

**Comment by JGulbronson** [comment]
@maniksurtani it's possible we could just use this, it seems to use v2 of Pagerduty's API: https://github.com/square/pagerduty-incidents

Thoughts?

**Comment by maniksurtani** [comment]
Sounds good.

**Comment by JGulbronson** [comment]
Going to close then. There's not much value in us adding it to Misk, unless we want to add automatic alerting for services. Can revisit at a later date.
