### ISSUE TITLE
Explicit config binding

### ISSUE THREAD

**Issue by mightyguava** [square/misk#794]
Currently, any subconfigs in the app's `Config` class are bound automatically by [ConfigModule](https://github.com/square/misk/blob/master/misk/src/main/kotlin/misk/config/ConfigModule.kt) via reflection, by discovering which sub-`Config`s are on the app `Config`. While this is convenient, there are a few important consequences

- It's difficult for a developer not intimately familiar with Guice and reflection to trace where a Config is bound, unless they had prior knowledge that the `ConfigModule` bound it all automatically
- It forces a heavy reliance on implicit injections for configs. If an app installs `FooModule()` and `BarModule()`, and the app does not define `FooConfig` and `BarConfig` in its app `Config`, `ConfigModule` will not bind these subconfigs, and Guice will just inject the implicit binding, if the config is fully covered by default values. This introduces a lot of inconsistency in tests, and developers end up unknowingly relying the implicit binding of the config (a "default" config basically). This can and has caused confusion, and makes it difficult/impractical to enable https://github.com/square/misk/issues/784.
- All subconfigs are available for injection, whether that is intended by the module design or not. For example, `HibernateModule` is meant to be qualified with an annotation, so it's unlikely that a top-level DataSourceClustersConfig/DataSourceConfig should be made injectable unqualified
- The name for the subconfig in the app `Config` matters. If the name of the subconfig in the YAML is not the lower_underscore case of its class name, it will get bound with an `@Named` annotation instead. Classes try try to inject this config without the qualifier will again get the implicit binding instead.

I'd like us to start explicitly binding sub-configs, making it the responsibility of the `Module` consuming the config object to choose to whether to bind it or not. Guice is magical enough. Misk should not make it more magical, but rather be an examplar of what is the best way to use Guice.

Before:
```kotlin
override func configure() {
  install(ConfigModule.create("my-app", myAppConfig)
  install(MiskWebModule())
  install(KubernetesClusterModule())
}
```

After:
```kotlin
override func configure() {
  install(ConfigModule.create("my-app", myAppConfig)
  install(MiskWebModule(myAppConfig.web_config))
  install(KubernetesClusterModule(myAppConfig.kubernetes_cluster_config))
}
```

The downside to the explicit config binding approach is of course that there will need to be additional code added to each config, and a ton of threading things through.

**Comment by ryanhall07** [comment]
what does installing the `ConfigModule` bind in the after?

**Comment by mightyguava** [comment]
This is what `ConfigModule` would look like after:

```
class ConfigModule<T : Config>(
  private val configClass: Class<T>,
  private val appName: String,
  private val config: T
) : KAbstractModule() {
  @Suppress("UNCHECKED_CAST")
  override fun configure() {
    bind<String>().annotatedWith<AppName>().toInstance(appName)
    bind(configClass).toInstance(config)
  }
}
```

It's possible we might not need it anymore, and we can just have it be `AppNameModule(appName)`.

**Comment by ryanhall07** [comment]
yea I'd much rather move the `AppName` binding out, seems like a weird spot for it.

in the spirit of being more clear about the config, maybe we don't bind it?

**Comment by mmihic** [comment]
What's the proposal for dealing with skim (which bundles together all of the modules required by applications, many of which require configuration)?  Since only the application knows the top-level config and the placement of the sub-configs, seems like either the application is forced to install all of the required modules explicitly (error prone) or we need to create a `SkimConfig` sub-config which contains sub-sub-configs for all required modules, and have the application pass this in to the `SkimModule` constructor.

**Comment by mightyguava** [comment]
I'd propose we add a `SkimConfig`. It'd be a good config parallel to `SkimModule` regardless.

**Comment by adrw** [comment]
For the purpose of the `config` dashboard tab, is there an way that Misk could aggregate all of the different configs for display if each sub-config is going to be bound on its own (ie. `SkimConfig`)? Currently it displays each of the raw config files from the filesystem (`common`, `staging`, `poduction`...) as well as a flattened version which is the `Effective Config` but there is no way right now to include and display bound configs from outside of Misk (like the database or Vitess ones applied by `Skim`).

**Comment by mightyguava** [comment]
> is there an way that Misk could aggregate all of the different configs for display if each sub-config is going to be bound on its own (ie. `SkimConfig`)?

How do I look at this config tab? If it shows the full merged config, that's the top-level config, which we should still be able to bind.

> But, there is no way right now to include and display bound configs from outside of Misk (like the database or Vitess ones applied by `Skim`)

Could you elaborate here? I'm not understanding this statement.

**Comment by adrw** [comment]
> How do I look at this config tab?

Any deployed service's Misk Admin Dashboard: `http://service.url.com/_admin/config/`

> Could you elaborate here?

The `Effective Config` displayed on the dashboard is generated here: https://github.com/square/misk/blob/fa7c583866260f1067f95f7a9af42912bfa20dfe/misk/src/main/kotlin/misk/config/ConfigAdminAction.kt

It's done by mapping over all of the local config files so the `Effective Config` unfortunately is a misleading name at this point because it doesn't include any config that Skim adds.
