### ISSUE TITLE
Secret Management

### ISSUE THREAD

**Issue by JGulbronson** [square/misk#8]
Misk should be opinionated about how secrets are stored, and force users to do so securely. This might use a service such as [Keywhiz](https://square.github.io/keywhiz/) directly, or it could support multiple backends such as [Vault](https://www.vaultproject.io/).

**Comment by maniksurtani** [comment]
But also what's native to a given environment. E.g., [KMS](https://cloud.google.com/kms/) on GCP.

**Comment by mmihic** [comment]
Correct - current plan is cloud native KMS offering key management and crypto routines, with storage of encrypted non-key materials left to the application
