### ISSUE TITLE
RealTokenGenerator::generate() does NOT make use of the `label` param

### ISSUE THREAD

**Issue by jjestrel** [square/misk#951]
if something like label = "C_" is passed in, I'd expect something like C_RF8FNG37 to come out
but it's not used

**Comment by swankjesse** [comment]
The label is only used by the fake generator. If you want a prefix, concatenate!

**Comment by swankjesse** [comment]
https://github.com/square/misk/blob/2c6f09f9cd95577a023d2172251507354fbc37e3/misk/src/main/kotlin/misk/tokens/TokenGenerator.kt#L5
